# Generated by Django 3.0.6 on 2020-05-23 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventaenc',
            name='cliente',
        ),
        migrations.DeleteModel(
            name='VentaDet',
        ),
        migrations.DeleteModel(
            name='VentaEnc',
        ),
    ]
