# Generated by Django 3.0.6 on 2020-06-27 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0003_facturabody_invertir'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturabody',
            name='invertir',
        ),
    ]
