# Generated by Django 3.0.6 on 2020-07-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0004_remove_facturabody_invertir'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturabody',
            name='ganancias',
            field=models.FloatField(default=0),
        ),
    ]
