# Generated by Django 3.0.6 on 2021-11-01 05:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0005_facturabody_ganancias'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturabody',
            name='fecha',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
