# Generated by Django 3.0.6 on 2021-11-01 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0006_facturabody_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturabody',
            name='fecha',
        ),
    ]
