# Generated by Django 3.0.6 on 2020-06-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regmedic', '0003_auto_20121101_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='co_fijo',
            field=models.CharField(blank=True, choices=[('0257', '0257'), ('0251', '0251'), ('0255', '0255'), ('0256', '0256'), ('0272', '0272')], max_length=20, null=True),
        ),
    ]
