# Generated by Django 2.2.4 on 2020-06-27 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regmedic', '0004_auto_20200627_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='co_fijo',
        ),
    ]
